### ISSUE TITLE
[debounce] Add proxy item initialization

### ISSUE THREAD

**Issue by pailloM** [rkoshak/openhab-rules-tools#27]
It can happen that when the debounce rule is created the main item is in a different state than the proxy item.
When this is the case it takes a couple of debounce cycles to get them back in sync.

To avoid this I would suggest to initialize the proxy item with the state of the main item when the rule is created. 

I have implemented it locally using the list generator debounce_items provided by load_rule_with_metadata in the function load_debounce.
I can submit a PR if you like, although not sure this is the correct place to do it. It might be preferable to do it before the rule creation.

It could be made optional with an additional key in the metadata as it is probably not required for items that switch state frequently.

**Comment by rkoshak** [comment]
Let me think on it a bit. I agree with the approach but also agree it could go in more than one place.

**Comment by rkoshak** [comment]
I went ahead and implemented it. There was a bug in the function that returns the list of debounce Items that needed to be fixed too.
