### ISSUE TITLE
[ephem_tod] Better error logging when init_items is not installed

### ISSUE THREAD

**Issue by rkoshak** [rkoshak/openhab-rules-tools#28]
Check to see if ItemInit exists and report a message suggesting it be installed when it is not present.

**Comment by CrazyIvan359** [comment]
Could do something like this:
(I have not checked any names) 

```python
try:
    from community.item_init import ItemInit
except ImportError:
    ' log message here
    ItemInit = None
```
Setting `ItemInit` to `None` solves the problem of hitting `variable not defined` errors when checking if the function is available. 

And then just before using the function you only have to check if it is `None`:
```python
if ItemInit is not None:
   ' do item init action
```

**Comment by rkoshak** [comment]
I was thinking an even easier way would be to just look for the Item. Since the Item is programmatically created and has a hard coded name I can just check to see if "InitItems" is in `items`:

```python
    null_items = [i for i in start_times if isinstance(items[i], UnDefType)]
    if null_items and "InitItems" in items:
        ephem_tod.log.warn("The following Items are are NULL: {} kicking off "
                           "initialization".format(null_items))
        events.sendCommand("InitItems", "ON")
        from time import sleep
        sleep(5)
    else:
        ephem_tod.log.error("The following Items are NULL and init_items is not available, cannot continue: {}".format(null_items))
        return
```

Admittedly that would be a less strong of a check as that Item might exist and the rule not. It also might be the case that the user has manually removed or disabled the rule so maybe the best approach would be to look to see if the rule itself exists and is enabled. That would be the definitive check. 

Furthermore, I should search through the Items again and make sure the init rule worked. But, if I check whether the rule worked I can go back to just seeing whether the Item exists. That should catch any number of errors with the init_items not being there or disabled or broken in some way.

I've been busy these last couple of weeks and have been rewriting sensorReporter as a first step to making it use the Homie standard so I've not come back to these to do even the simple updates like this.

**Comment by CrazyIvan359** [comment]
I haven't had a chance to test anything out, I was just reading through some of your work.

Would you not be checking for valid item states before taking action in a step shortly after this?

**Comment by rkoshak** [comment]
As written right now, if it sees any Items that are NULL or UNDEF, it tries to trigger an initialization of the Items using the item_init Rule. Then it waits for five seconds and just assumes that all the Items became initialized. If that failed than errors will be thrown but they won't be nice "This happened, do this to fix it" type errors that I prefer to generate when I can.

So I think I need to check again after the five second sleep to make sure the Items are no longer NULL/UNDEF. If they are, generate a nice error with advice for how to fix the problem and exit the rule.

**Comment by CrazyIvan359** [comment]
I agree with you there, I think having a message for every item every time it runs is actually better. It will make debugging easier than if it only logged something on script load when trying to see why your init values are not being used by ToD.

**Comment by CrazyIvan359** [comment]
I agree with you there, I think having a message for every item every time it runs is actually better. It will make debugging easier than if it only logged something on script load when trying to see why your init values are not being used by ToD.

**Comment by rkoshak** [comment]
Implemented.
