### ISSUE TITLE
[ephem_tod] When there isn't a time near midnight, the timers don't get scheduled correctly

### ISSUE THREAD

**Issue by rkoshak** [rkoshak/openhab-rules-tools#35]
Somewhere there is a bug, perhaps 2. 

1. When there is a big gap between the last event of the day and the first event of the day, it may miscalculate the current time of day.

2. At least one person is reporting that the timers are not being created correctly. It sees all the FUTURE events but only one timer gets created.

**Comment by pailloM** [comment]
I had the same issue today. See log attached

The rule is triggered many times after midnight, basically every time the astro binding refreshes one of the item with the etod metadata. This behavior is expected however the scripts creates either 5 timers or 0 timers in a loop. The last time the rule ran 0 timer were created. I suspect there are multiple threads creating the timers and deleting them.
A lock should be implemented either in the rule or the timer manager class so only one thread can access the timer class at a time.

There is another issue with the reload timer. As it is deleted / created every time the function ephem_tod is called, when the astro binding refreshes the items just after midnight the reload timer is rescheduled for the next day meaning it never runs and is always rescheduled for the next day.
A simple logic to check whether the reload time for today is in the past or in the future could be implemented to reschedule the timer only if it is in the past

[log.txt](https://github.com/rkoshak/openhab-rules-tools/files/5222095/log.txt)

**Comment by rkoshak** [comment]
That was my first thought but a lock is already built in. With the NGRE/JSR223, only one instance of a rule can run at a time and the rest of the triggers queue up in a FIFO. Since that is the case and the TimerMgr is only accessed by this one rule a lock won't address the problem. It's already essentially locked.

You can see this in practice in the logs. Each time the rule triggers you will see it run from beginning to end in the logs before it runs again and again (depending on how many Items you have changing around midnight). If it were running them concurrently you would see the logs interleaved as the triggers are coming in faster than the rule can run.

I will definitely implement the second suggestion though. I should have done that to begin with.

**Comment by pailloM** [comment]
You are correct. I implemented a lock last night and had the same issue.
It happens when the timers already exists.
although timers.cancel_all() is called, the cancel all function in the timer manager does not cancel the keys and reschedule is not passed as an argument to the timer check function. so the timer manager check function cancels the timer and delete the key.

**Comment by rkoshak** [comment]
Based on some initial testing this seems to be resolved. Are you still seeing the problem pailloM? I've tested with the changes last night and it seemed to work. I'll leave this open a couple more days just in case but I think it's fixed. Thanks!

**Comment by pailloM** [comment]
I haven't had the issue with these 2 changes implemented. I believe it is fixed

**Comment by rkoshak** [comment]
So far it looks like this fixed the problem. Closing this issue as fixed. Thanks again!
