### ISSUE TITLE
[openhab-js 4] Review for breaking changes and update syntax

### ISSUE THREAD

**Issue by rkoshak** [rkoshak/openhab-rules-tools#78]
I don't think there are any breaking changes but I only did a cursory look. This is to remind me to look more carefully.

I also need to update the syntax to take advantage of changes in the openhab-js library.

I do not intend this to apply to rule templates which I'm doing one by one independently from the library.

- [x] countdownTimer
- [x] deferred
- [x] gatekeeper
- [x] groupUtils
- [x] helpers
- [x] loopingtimer
- [x] rateLimit
- [x] rulesUtils
- [x] testUtils
- [x] timerMgr
- [x] timeUtils

See https://github.com/rkoshak/openhab-rules-tools/pull/107 .

**Comment by rkoshak** [comment]
There are no breaking changes at least up through openhab-js 4.2.0 and in fact all the Timer classes depend on 4.2.0 for certain `when` types. I still need to do the syntax update though so I'll keep this open for now.

**Comment by einalex** [comment]
I think something broke your dadMotionTimer example.
timers.check dies for me. It seems like it tries to convert ZDT to ZDT.

2023-07-29 09:40:50.174 [ERROR] [b.automation.script.file.bathroom.js] - Failed to execute rule BathroomLightOff: Error: "2023-07-29T09:41:00.153Z[SYSTEM]" is an unsupported type for conversion to time.ZonedDateTime: Error: "2023-07-29T09:41:00.153Z[SYSTEM]" is an unsupported type for conversion to time.ZonedDateTime
	at toZDT (/node_modules/openhab.js:2)
	at check (/etc/openhab/automation/js/node_modules/openhab_rules_tools/timerMgr.js:46)

**Comment by rkoshak** [comment]
Which version of the openhab-js library are you using? `toZDT` lives there now and there were some changes made so that it should support RFC type strings like that now. Recent versions have a `utils.OPENHAB_JS_VERSION` that contains the library version. 

As for "dadMotionTimer", are you referring to a specific tutorial or design pattern, or an example that comes from the Threshold Alert rule tempalte?

**Comment by einalex** [comment]
> Which version of the openhab-js library are you using?

latest available via npm I think, variable says 4.5.0

> As for "dadMotionTimer", are you referring to a specific tutorial or design pattern, or an example that comes from the Threshold Alert rule tempalte?

code copied from the discourse thread where the tools were presented.

**Comment by rkoshak** [comment]
> code copied from the discourse thread where the tools were presented.

That's where I'm confused as there is no mention of "dadMotionTimer" at https://community.openhab.org/t/announcing-the-initial-release-of-openhab-rules-tools/132032

I don't know where else I've written that example by that name so 🤷 .

**Comment by rkoshak** [comment]
See #107 .

**Comment by einalex** [comment]
https://community.openhab.org/t/some-js-scripting-ui-rules-examples/131305#dad-motion-11
this one

**Comment by rkoshak** [comment]
I've run with #107 for awhile and it all checks out. I'm closing this now.
