### ISSUE TITLE
Get rid of Joda DateTime

### ISSUE THREAD

**Issue by rkoshak** [rkoshak/openhab-rules-tools#9]
Several of these libraries use Joda DateTime. Joda is removed in OH 3 so these need to be changed as appropriate prior to OH 3's release.

**Comment by pailloM** [comment]
I would like to have the time_utils module functions to return python datetime objects as well as Joda DateTime.

What would be your preferred approach regarding modifying the time_utils module:

- adding an optional argument to functions to select which type of datime to return, something like this: ouput=Joda or python=False in order not to break current implementations

- create new functions

- create a new module

**Comment by rkoshak** [comment]
Well, my main intent for this Issue is to move from Joda DateTime to Java ZonedDateTime which is what is replacing Joda DateTime in OH 3 and is what will be needed to schedule Timers in OH 3.

Also, don't forget the Helper Libraries have a lot of DateTime functions for converting to and from Python date time as well as a number other helpful date time functions. I'm hesitant to encroach on anything that the Helper libraries already implement. I do not intend this library to compete with the Helper Libraries and in fact intend on trying to submit them to the Helper Library when PRs to the community start being reviewed and accepted. 

When I first wrote this module I only considered the use case of scheduling Timers. And sort of time math and conversions is already pretty well handled by the Helper Library.

So my question back is:

- which functions do you want to return Python DateTimes?
- what would adding this add over what the Helper Libraries already provide (see core.date  https://openhab-scripters.github.io/openhab-helper-libraries/Python/Core/Packages%20and%20Modules/date.html)
- what use case do you have in mind?

All things considered my first priority would be backwards compatibility. No change should force changes to code that already uses the functions. I don't think a new module is required. Beyond that, I'd like to look at PEP8 to see what the most Pythonic approach would be; assuming that we are not stepping on the Helper Library's toes.

**Comment by pailloM** [comment]
In a few rules I am using python time or datetime objects which i need to convert to todays date. My initial idea was to use the time_utils function to_today but it returns only a joda date time object and does not support time object as input. 
Parse duration already returns a python timedelta object.
So it would be to add support for these 2 functions: to_today and to_datetime

If the primary use case for this library is to use the timer manager module, then we could add a check on the timer manager module to check what input is provided and use the core function to_joda_datetime to convert the time input if it is python or java?
So the time_utils library could return only zoneddatetime or python datetime. It would make it easier to remove joda datetime in the other rules like etod.

If the to_today and parse_duration function can be added to core.date that would be great! I don't want to reinvent the wheel, I make heavy use of the core.date functions.

I have attached a draft pull request to show what it could look like. It is not ready and not fully functional either there are some use cases that throws exceptions. Before doing anymore I would like your input to understand if I am doing something that is useful.

**Comment by rkoshak** [comment]
> If the primary use case for this library is to use the timer manager module

It's used pretty much everywhere Timers are created in openhab-rules-tools. So it's reach extends beyond just TimerMgr. If it were only used by TimerMgr I'd probably not have extracted it into it's own library. But it was created mostly to work with the Timer related modules like countdown_timer, looping_timer, etc. I'm not completely against adding this but it seems like it adds a whole lot of complexity to the library only to let the users avoid calling `core.date.to_python_datetime` when needed. 

I can see the use for updating to_today, but I think there too there is a one liner pythonic way to do it.

Please do add test cases to the testing script to cover all the additions you are making. This library is used all over the place in other scripts and modules so we need it to be rock solid.

**Comment by pailloM** [comment]
I agree it adds a lot of complexity to this library. Hopefully it makes it easier to remove joda date time dependencies in the other scripts

Working on the tests

**Comment by rkoshak** [comment]
Since the PR was merged this issue can be closed. The JavaScript versions I'm porting to do not include Joda DateTime at all.
